##############################################################################
# Copyright (c) 2018 Dell EMC and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

heat_template_version: 2013-05-23

parameters:
  volume_size:
    type: number
    description: Size of the volume to be created.
    default: 1
    constraints:
      - range: { min: 1, max: 1024 }
        description: must be between 1 and 1024 Gb.
  agent_instance_uuid:
    type: string

resources:
  agent_volume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: volume_size }

  agent_volume_att:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_param: agent_instance_uuid }
      volume_id: { get_resource: agent_volume}
